### PR TITLE
Added to_array

### PR DESCRIPTION
**Pull request by anarthal**

### CODE REVIEW

**Comment by pdimov** [comment]
1. the static asserts don't actually test what the code requires. The array elements are of type `remove_cv_t<T>`, not `T`, so the conditions being asserted should be `is_constructible<remove_cv_t<T>, T&>` and `is_constructible<remove_cv_t<T>, T&&>` respectively.
2. documentation
3. the tests should test const input elements, e.g. `int const`, `std::vector<int> const`.
4. the constexpr tests should still check that the result is correct (at runtime).

**Comment by anarthal** [comment]
Regarding 1. [cppreference](https://en.cppreference.com/w/cpp/container/array/to_array) it states it as I wrote it - is it a defect in cppreference?

**Comment by pdimov** [comment]
cppreference correctly reflects what the standard says in https://eel.is/c++draft/array.creation, but I think that this is a defect in the standard. I'll ask.

**Comment by pdimov** [comment]
Please add lvalue tests for `const int` and l/rvalue tests for const.

Also, let's use the correct `is_constructible<remove_cv_t<T>, T&>` in both code and docs, regardless of what the standard says.

**Comment by pdimov** [comment]
No, sorry. The array elements being constructed are of type `remove_cv_t<T>`. The arguments are of type `T&` or `T&&` respectively. Ergo, the conditions are `is_constructible<remove_cv_t<T>, T&>` and `is_constructible<remove_cv_t<T>, T&&>`, respectively.

**Comment by anarthal** [comment]
Long day yesterday. Should be fixed now. If I've understood this correctly, using `remove_cvref_t` doesn't make sense because C arrays can't contain references, and thus `remove_cv_t` is more accurate.

I've left the multi-dimensional checking condition as `is_array<T>` because `is_array<const/volatile int[N]>` is also true.

**Pull request merged**
